apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-network-policy
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: database

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        # allow backend pods
        - podSelector:
            matchLabels:
              app: backend

        # allow postgres-exporter to talk to db
        # for metrics collection
        - podSelector:
            matchLabels:
              app: postgres-exporter

      ports:
        - protocol: TCP
          port: {{ .Values.database.service.targetPort }}

  # no egress rules listed, postgres never initiates outbound traffic