apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
  namespace: {{ .Values.global.namespace }}
  
spec:
  replicas: {{ .Values.database.replicaCount }}
  serviceName: database-service

  selector:
    matchLabels:
      app: database

  template:
    metadata:
      labels:
        app: database

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.database.service.targetPort }}

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_DB
            
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER
            
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD

          resources:
          {{- toYaml .Values.database.resources | nindent 12 }}

          # add health probes
          # use exec instead of httpGet
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.auth.postgresUser }}
                - -d
                - {{ .Values.database.auth.postgresDB }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.database.auth.postgresUser }}
                - -d
                - {{ .Values.database.auth.postgresDB }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.database.storage.size }}
