apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
  - namespace.yml
  - backend/backend-secret.yml
  - backend/configMap.yml
  - backend/deployment.yml
  - backend/service.yml
  - frontend/configMap.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - database/database-secret.yml
  - database/service.yml
  - database/statefulset.yml
  - policies/database-policy.yml
  - policies/resource-quota.yml
  - ingress/ingress.yml