---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: backend
spec:
  encryptedData:
    DATABASE_URL: AgB/+xmcdk0ajP+Xe8C/Qdk0SYQtpA8O0xJfN/s0VslpX+giJM31wzBuQaHRHuYjhDjRBbnd2nNmb625x5TMvPhD4GsaXChd1IgY6ZQ8t7LkAnQyWWKujH7YXIIibR44y3TB+4LIuDAzq+8lXJVRvx2TQiUkrc30PDwg99d8yfZEfD0zgk1NRUrVz325Nif8PBRvjUMUdFQChZytEXYT5X349/CWU4KEgSl4SSIwm3k07y44yKa6emr+s5s7c1VpI68IX7qkqFefsxrU4Ga7o28cXTmkALMwp83nZcYm26LpbYfcot/X8Pq9YMeOXeWbBx9V9Hs1wqY+RBY+5QAkBqKneTgn6+8TBFVuLBITS00IfxA+osK1yiz0BpPStKGLNFV0QnpRvsKAKMIptd/R8gVtbT2yYU2e8h7CEjkc2wyyoc3fC603hYxNzekL/xBaD0znIvuh6vdUUuVvDNTrPafUUTyn2S9KIfI2kitkGCpM1SlE3efCJb9JodjZhyYbAw2ayfWNS5X+fXaOA/fY3TgKnVg00CWvzqXonfBR19g5pn//qCt5F1SoyUFZjWFuwUHeOTgiUSq60jeby+9D84mcu3IjiDPfZR0MrTMjKbEHieUKkoCA5qdCgQAE+ee9btSO8hD6j20Fblk2Y1F4HCULPDvgB3qsZZPZU/4rAiN6O7BTCqlxDxwTZ3V8Ai3LawWvpqwTxh+8fXz9uVuEyWbwgv2IuUzDNo2ZLCzdrtdIVuZ3u6ObMXrgSJbAmYrtckameOfbim5sov1RC/woSmrysOIydR4jEJQ6tGwrp/mG
  template:
    metadata:
      name: backend-secret
      namespace: backend
    type: Opaque
