apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RlZXA6c210aG5AcG9zdGdyZXMtc2VydmljZS5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2s4cy1kYg==
