name: todo-app

services:
  backend:
    build:
      context: ./backend
    container_name: todo-app-backend

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    container_name: todo-app-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    networks:
      - my_network

  postgres:
    image: postgres:16-alpine
    container_name: todo-app-pg
    restart: unless-stopped

    environment:
      POSTGRES_USER: deep
      POSTGRES_PASSWORD: smthn
      POSTGRES_DB: todo-db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deep -d todo-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
      - "5432:5432"

    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
