apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend
spec:
  hard:
    requests.cpu: "300m"
    requests.memory: "384Mi"
    limits.cpu: "600m"
    limits.memory: "768Mi"
    pods: "10"
