---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    DATABASE_URL: AgBi4wnGIlTRyYr1BzwWI3BlABxkxBs6Sq9C98CuBMydmrzQD+7uMPTIU1/QEi+iF2pC/UJcEgvBIWWzSydkUebdmeQORJIPAl98v2FWGLIzbHxNxeZzRiSOufHTuQcfcsYTvQoMi8+weXylfe6FnIeYn7ftp92ZT5ZAnmMI4SAyODhcmgiuIvYP03oUB6WCWaWtHr3/q8CDafVV8FnffGy30fb6dLzVIG26EFgYwXYR/H5KGzvuX3Mxq5jB4kea+F543nb6QaFW8a/hPTQ5Y7AJNoMNs3CYeQtdqPeGshusmQD7os7fc6Cq3ALAZnFbNAEegy1EWqbNA6BOXxS9IezlNmp6CmGL/jr5bwyoyXMy0jTYeODqLzytlITPjZ64beof5iDNZB8YNWTYzFvfwiAC880fHI4oWEdefJyUmCzl1AhA6OZPemRLPZYwl4/7kGhyeIwYk8mOQF4nUJ0ewnirHavjoAnD7tmwBK7O0kHi6UavaKksMMSsFdQAWM/po8JSOI+qoQlRCHKOvnvbrAazxW8FSwTV2ZzFW/j/axN4ysqh6m+8n2MgbZcx7Fh2ChkWPGtb7z4sv/4SP989cOMtkscsbTpwIKaYA/JAYn2U+0+OX2aWufN54qXdZuiprvqFqlDESHu/0SkKeyQFdnta+mHRAmy7jOM99faY5Jv4YSethmNPyE7a7nWM8YORrPEzIUk5+KDAJOoJlDj27veQ9SpckSi4VnyGKmRVa49iY6/2sudp9n/voqOhGR/LyFbLaKCiyJAZXG3hM2aWLDp3
  template:
    metadata:
      name: backend-secret
      namespace: {{ .Values.global.namespace }}
    type: Opaque
