apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: {{ .Values.global.namespace }}
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s