grafana:
  adminPassword: admin # set the password for user admin

  # enable persistent storage
  persistence:
    enabled: true
    type: pvc
    size: 5Gi

    accessModes:
      - ReadWriteOnce

prometheus:
  prometheusSpec:
    retention: 7d # TSDB data is stored for 7 days
