global: # shared accross the app
  namespace: todo-app
  env: dev
  domain: todo-app.local
# component specific
backend:
  replicaCount: 4
  image:
    repository: ghcr.io/deepsoumyaaa/todo-app-backend
    tag: sha-66c04ab0dd89d3b98cab4bb358b6f5ed45862839
    pullPolicy: IfNotPresent
  service:
    port: 80
    targetPort: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 60
    # targetMemoryUtilizationPercentage: 70

    behavior:
      scaleUp:
        stabilizationWindowSeconds: 0
      scaleDown:
        stabilizationWindowSeconds: 300
frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/deepsoumyaaa/todo-app-frontend
    tag: sha-fb7646d61c7485b05b5b2669d305ff5a3c5f3c88
    pullPolicy: IfNotPresent
  service:
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
database:
  replicaCount: 1
  image:
    repository: postgres
    tag: "16"
  # we can omit targetPort if both are same
  service:
    port: 5432
    targetPort: 5432
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  auth:
    postgresDB: todo-db
    postgresUser: deep
    postgresPassword: smthn
# export postgres metrics via postgres-exporter
postgresExporter:
  enabled: true
  replicaCount: 1
  image:
    repository: prometheuscommunity/postgres-exporter
    tag: v0.20.1
    pullPolicy: IfNotPresent
  service:
    port: 9187
    targetPort: 9187
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
# Resource Quota configuration
resourceQuota:
  enabled: true
  requests:
    cpu: "2"
    memory: "2Gi"
  limits:
    cpu: "4"
    memory: "4Gi"
  pods: "15"
  services: "10"
# enable ingress
ingress:
  enabled: true
  className: nginx
  tls:
    enabled: false
# disable default-deny-networkpolicy
networkPolicy:
  defaultDenyEnabled: false
