apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
type: Opaque
# base64 encoded
data:
  POSTGRES_USER: ZGVlcA==
  POSTGRES_PASSWORD: c210aG4=
  POSTGRES_DB: dG9kby1kYg==
