apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@database-service:%d/%s" .Values.database.auth.postgresUser .Values.database.auth.postgresPassword (.Values.database.service.port | int) .Values.database.auth.postgresDB | b64enc | quote }}
