grafana:
  adminPassword: admin # set the password for user admin
  # load the dashboards automatically
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL

# production options
#   # enable persistent storage
#   persistence:
#     enabled: true
#     type: pvc
#     size: 5Gi

#     accessModes:
#       - ReadWriteOnce

# prometheus:
#   prometheusSpec:
#     retention: 7d # TSDB data is stored for 7 days
