# disable all default
# i dont want a lot of bs alerts on my telegram
defaultRules:
  create: false

grafana:
  adminPassword: admin # set the password for user admin
  # load the dashboards automatically
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  # add loki as an additional data source
  additionalDataSources:
    - name: loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      access: proxy
      isDefault: false

alertmanager:
  config:
    global:
      resolve_timeout: 2m
    route:
      group_by: ["alertname", "namespace"]
      group_wait: 5s
      group_interval: 30s
      repeat_interval: 1h
      receiver: "telegram-notifications"
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: "null"
    receivers:
      - name: "null"
      - name: "telegram-notifications"
        telegram_configs:
          - bot_token: "<TELEGRAM_BOT_TOKEN>"
            chat_id: <CHAT_ID>
            send_resolved: true
            parse_mode: HTML

prometheus:
  prometheusSpec:
    retention: 1d
    evaluationInterval: 15s
    scrapeInterval: 15s
    ruleSelector:
      matchLabels:
        release: monitoring
    ruleNamespaceSelector: {}
