apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.data.postgresDB | b64enc }}
  POSTGRES_USER: {{ .Values.database.data.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.database.data.postgresPassword | b64enc }}
